<?
  define('siteName', 'Новый сайт');
  define('siteTitle', 'Новый сайт');
  define('siteTitleReverse', true);
  define('siteKeywords', '');
  define('siteDescription', '');
  define('mailFromAddr', '');
  define('mailFromName', '');
  define('mailFromOrg', '');
  define('mailReplyTo', '');
  define('mailCharset', 'windows-1251');
  define('mailFromSign', "Система управления сайтом\r\nEresus");
  define('sendNotifyTo', '');
  define('filesOwnerSetOnUpload', false);
  define('filesOwnerDefault', '');
  define('filesModeSetOnUpload', true);
  define('filesModeDefault', '0644');
  define('contentTypeDefault', 'html');
  define('pageTemplateDefault', 'default');
?>