<?php
class Sections_fake {
	protected $index = array (
		0 => array(3, 1, 4, 5, 6, 7,	2, 16, 17),
		5 => array(18, 19, 20),
		1 => array(22),
		4 => array(21),
		3 => array(8, 9, 10, 12, 11),
	);
	protected $data = array (
		1 => array (
			'id' => '1',
			'name' => 'main',
			'owner' => '0',
			'title' => 'Main page title',
			'caption' => 'Main page',
			'description' => 'Main page description',
			'hint' => 'Main page hint',
			'keywords' => '',
			'position' => '0',
			'active' => '1',
			'access' => '5',
			'visible' => '1',
			'template' => 'default',
			'type' => 'html',
			'options' => 'a:0:{}',
			'created' => '0000-00-00 00:00:00',
			'updated' => '2008-05-16 11:01:50',
		),
		3 => array (
			'id' => '3',
			'name' => 'services',
			'owner' => '0',
			'title' => 'Услуги',
			'caption' => 'Услуги',
			'description' => '',
			'hint' => '',
			'keywords' => '',
			'position' => '1',
			'active' => '1',
			'access' => '5',
			'visible' => '1',
			'template' => 'default',
			'type' => 'articles',
			'options' => 'a:0:{}',
			'created' => '2007-11-09 14:35:08',
			'updated' => '2008-05-16 11:01:50',
		),
		8 => array (
			'id' => '8',
			'name' => 'sources',
			'owner' => '3',
			'title' => 'Какие материалы мы используем',
			'caption' => 'Какие материалы мы используем',
			'description' => '',
			'hint' => '',
			'keywords' => '',
			'position' => '0',
			'active' => '1',
			'access' => '5',
			'visible' => '1',
			'template' => 'default',
			'type' => 'html',
			'options' => '',
			'created' => '2007-11-09 14:50:58',
			'updated' => '2007-11-09 14:50:58',
		),
		22 => array (
			'id' => '22',
			'name' => 'main_child',
			'owner' => '1',
			'title' => 'main_child title',
			'caption' => 'main_child caption',
			'description' => '',
			'hint' => '',
			'keywords' => '',
			'position' => '0',
			'active' => '1',
			'access' => '5',
			'visible' => '1',
			'template' => 'default',
			'type' => 'html',
			'options' => '',
			'created' => '2008-05-16 11:00:42',
			'updated' => '2008-05-16 11:00:42',
		),
		18 => array (
			'id' => '18',
			'name' => 'gallery1',
			'owner' => '5',
			'title' => 'Галлерея 1',
			'caption' => 'Галлерея 1',
			'description' => '',
			'hint' => '',
			'keywords' => '',
			'position' => '0',
			'active' => '1',
			'access' => '5',
			'visible' => '1',
			'template' => 'default',
			'type' => 'fgallery',
			'options' => '',
			'created' => '2008-04-24 14:59:58',
			'updated' => '2008-04-24 14:59:58',
		),
		21 => array (
			'id' => '21',
			'name' => 'gallery4',
			'owner' => '4',
			'title' => 'Галлерея 4',
			'caption' => 'Галлерея 4',
			'description' => '',
			'hint' => '',
			'keywords' => '',
			'position' => '0',
			'active' => '1',
			'access' => '5',
			'visible' => '1',
			'template' => 'default',
			'type' => 'fgallery',
			'options' => '',
			'created' => '2008-04-24 15:28:47',
			'updated' => '2008-04-24 15:28:47',
		),
		9 => array (
			'id' => '9',
			'name' => 'order',
			'owner' => '3',
			'title' => 'Какие сделать заказ',
			'caption' => 'Какие сделать заказ',
			'description' => '',
			'hint' => '',
			'keywords' => '',
			'position' => '1',
			'active' => '1',
			'access' => '5',
			'visible' => '1',
			'template' => 'default',
			'type' => 'webform',
			'options' => 'a:2:{s:8:"allowGET";s:0:"";s:6:"mailto";s:14:"mk@procreat.ru";}',
			'created' => '2007-11-09 14:51:14',
			'updated' => '2007-12-10 13:03:16',
		),
		19 => array (
			'id' => '19',
			'name' => 'gallery2',
			'owner' => '5',
			'title' => 'Галлерея 2',
			'caption' => 'Галлерея 2',
			'description' => '',
			'hint' => '',
			'keywords' => '',
			'position' => '1',
			'active' => '1',
			'access' => '5',
			'visible' => '1',
			'template' => 'default',
			'type' => 'fgallery',
			'options' => '',
			'created' => '2008-04-24 15:01:02',
			'updated' => '2008-04-24 15:01:02',
		),
		4 => array (
			'id' => '4',
			'name' => 'shop',
			'owner' => '0',
			'title' => 'Фотомагазин',
			'caption' => 'Фотомагазин',
			'description' => '',
			'hint' => '',
			'keywords' => '',
			'position' => '2',
			'active' => '1',
			'access' => '5',
			'visible' => '1',
			'template' => 'default',
			'type' => 'fgallery_mod',
			'options' => 's:0:"";',
			'created' => '2007-11-09 14:35:38',
			'updated' => '2008-04-24 15:28:25',
		),
		10 => array (
			'id' => '10',
			'name' => 'prepare',
			'owner' => '3',
			'title' => 'Подготовка к печати',
			'caption' => 'Подготовка к печати',
			'description' => '',
			'hint' => '',
			'keywords' => '',
			'position' => '2',
			'active' => '1',
			'access' => '5',
			'visible' => '1',
			'template' => 'default',
			'type' => 'html',
			'options' => '',
			'created' => '2007-11-09 14:51:26',
			'updated' => '2007-11-09 14:51:26',
		),
		20 => array (
			'id' => '20',
			'name' => 'gallery3',
			'owner' => '5',
			'title' => 'Галлерея 3',
			'caption' => 'Галлерея 3',
			'description' => '',
			'hint' => '',
			'keywords' => '',
			'position' => '2',
			'active' => '1',
			'access' => '5',
			'visible' => '1',
			'template' => 'default',
			'type' => 'fgallery',
			'options' => '',
			'created' => '2008-04-24 15:01:23',
			'updated' => '2008-04-24 15:01:23',
		),
		5 => array (
			'id' => '5',
			'name' => 'gallery_toc',
			'owner' => '0',
			'title' => 'Оглавление фотогалереи',
			'caption' => 'Оглавление фотогалереи',
			'description' => '',
			'hint' => '',
			'keywords' => '',
			'position' => '3',
			'active' => '1',
			'access' => '5',
			'visible' => '1',
			'template' => 'default',
			'type' => 'fgallery_mod',
			'options' => 's:0:"";',
			'created' => '2007-11-09 14:36:31',
			'updated' => '2008-04-24 14:51:50',
		),
		6 => array (
			'id' => '6',
			'name' => 'photos',
			'owner' => '0',
			'title' => 'Фотоальбом',
			'caption' => 'Фотоальбом',
			'description' => '',
			'hint' => '',
			'keywords' => '',
			'position' => '4',
			'active' => '1',
			'access' => '5',
			'visible' => '1',
			'template' => 'default',
			'type' => 'gallery',
			'options' => 's:0:"";',
			'created' => '2007-11-09 14:38:59',
			'updated' => '2007-12-06 20:46:27',
		),
		11 => array (
			'id' => '11',
			'name' => 'recomendations',
			'owner' => '3',
			'title' => 'Рекомендации',
			'caption' => 'Рекомендации',
			'description' => '',
			'hint' => '',
			'keywords' => '',
			'position' => '4',
			'active' => '1',
			'access' => '5',
			'visible' => '1',
			'template' => 'default',
			'type' => 'html',
			'options' => 'a:0:{}',
			'created' => '2007-11-09 14:51:41',
			'updated' => '2008-04-25 16:28:11',
		),
		12 => array (
			'id' => '12',
			'name' => 'delivery',
			'owner' => '3',
			'title' => 'Доставка курьером',
			'caption' => 'Доставка курьером',
			'description' => '',
			'hint' => '',
			'keywords' => '',
			'position' => '4',
			'active' => '1',
			'access' => '5',
			'visible' => '1',
			'template' => 'default',
			'type' => 'html',
			'options' => '',
			'created' => '2007-11-09 14:52:00',
			'updated' => '2007-11-09 14:52:00',
		),
		7 => array (
			'id' => '7',
			'name' => 'contacts',
			'owner' => '0',
			'title' => 'Контакты',
			'caption' => 'Контакты',
			'description' => '',
			'hint' => '',
			'keywords' => '',
			'position' => '5',
			'active' => '1',
			'access' => '5',
			'visible' => '1',
			'template' => 'default',
			'type' => 'html',
			'options' => 'a:0:{}',
			'created' => '2007-11-09 14:39:14',
			'updated' => '2007-11-09 14:39:31',
		),
		2 => array (
			'id' => '2',
			'name' => 'map',
			'owner' => '0',
			'title' => 'Карта сайта',
			'caption' => 'Карта сайта',
			'description' => NULL,
			'hint' => NULL,
			'keywords' => NULL,
			'position' => '6',
			'active' => '1',
			'access' => '5',
			'visible' => NULL,
			'template' => 'default',
			'type' => 'sitemap',
			'options' => 'a:0:{}',
			'created' => '2007-11-09 11:39:38',
			'updated' => '2007-11-09 14:39:31',
		),
		16 => array (
			'id' => '16',
			'name' => 'news',
			'owner' => '0',
			'title' => 'Новости',
			'caption' => 'Новости',
			'description' => '',
			'hint' => '',
			'keywords' => '',
			'position' => '7',
			'active' => '1',
			'access' => '5',
			'visible' => '1',
			'template' => 'default',
			'type' => 'news',
			'options' => '',
			'created' => '2008-03-07 13:14:54',
			'updated' => '2008-03-07 13:14:54',
		),
		17 => array (
			'id' => '17',
			'name' => 'test',
			'owner' => '0',
			'title' => 'Тест',
			'caption' => 'Тест',
			'description' => '',
			'hint' => 'Тест',
			'keywords' => '',
			'position' => '8',
			'active' => '1',
			'access' => '5',
			'visible' => '1',
			'template' => 'default',
			'type' => 'html',
			'options' => '',
			'created' => '2008-04-07 11:19:11',
			'updated' => '2008-04-07 11:19:11',
		),
	);
	/**
	 * Возвращает идентификаторы дочерних разделов указанного
	 *
	 * @access public
	 *
	 * @param  int  $owner   Идентификатор корневого раздела ветки
	 * @param  int  $access  Минимальный уровень доступа
	 * @param  int  $flags   Флаги (см. SECTIONS_XXX)
	 *
	 * @return  array  Идентификаторы разделов
	 */
	function children($owner, $access = GUEST, $flags = 0)
	{
		$result = array();

		$ids = isset($this->index[$owner]) ? $this->index[$owner] : array();
		foreach($ids as $id) $result[] = $this->data[$id];

		return $result;
	}
	//-----------------------------------------------------------------------------
 /**
	* Возвращает раздел
	*
	* @access public
	*
	* @param  int     $id  ID раздела
	* или
	* @param  array   $id  Список идентификаторов
	* или
	* @param  string  $id  SQL-условие
	*
	* @return  array  Описание раздела
	*/
	function get($id)
	{
		return $this->data[$id];
	}
	//------------------------------------------------------------------------------
}
?>