<?php
$GLOBALS['classes']['tclass']= 'tclass/class.php';
$GLOBALS['classes']['tclass_admin']= 'tclass/class_admin.php';

$GLOBALS['classes']['users']= 'users/users.php';
$GLOBALS['classes']['users_admin']= 'users/users_admin.php';
$GLOBALS['classes']['user']= 'users/user.php';
$GLOBALS['classes']['user_admin']= 'users/user_admin.php';
$GLOBALS['classes']['group']= 'users/group.php';
$GLOBALS['classes']['group_admin']= 'users/group_admin.php';

$GLOBALS['classes']['profile']= 'profile/profile.php';
$GLOBALS['classes']['profile_admin']= 'profile/profile_admin.php';
?>